import type { Theme } from '@/types';

export const themes: Theme[] = [
  {
    name: 'Marcas Famosas',
    slug: 'brands',
    images: [
      '/assets/images/marcas/apple.png',
      '/assets/images/marcas/dell.webp',
      '/assets/images/marcas/fiat.png',
      '/assets/images/marcas/google.png',
      '/assets/images/marcas/insider.webp',
      '/assets/images/marcas/mc-donalds.webp',
      '/assets/images/marcas/slack.png',
      '/assets/images/marcas/subway.png',
      '/assets/images/marcas/whatsapp.webp',
      '/assets/images/marcas/youtube.png',
    ],
  },
  {
    name: 'Linguagens de Programação',
    slug: 'languages',
    images: [
      '/assets/images/linguagens-de-programacao/c.png',
      '/assets/images/linguagens-de-programacao/c-plus-plus.png',
      '/assets/images/linguagens-de-programacao/c-sharp.png',
      '/assets/images/linguagens-de-programacao/java.png',
      '/assets/images/linguagens-de-programacao/javascript.jpg',
      '/assets/images/linguagens-de-programacao/node-js.png',
      '/assets/images/linguagens-de-programacao/php.png',
      '/assets/images/linguagens-de-programacao/python.webp',
      '/assets/images/linguagens-de-programacao/ruby.png',
      '/assets/images/linguagens-de-programacao/typescript.svg',
    ],
  },
  {
    name: 'Desenhos Animados',
    slug: 'cartoons',
    images: [
      '/assets/images/desenho-animado/bart-simpson.png',
      '/assets/images/desenho-animado/coragem.jpg',
      '/assets/images/desenho-animado/hora-da-aventura.jpg',
      '/assets/images/desenho-animado/mickey.webp',
      '/assets/images/desenho-animado/pantera-cor-de-rosa.png',
      '/assets/images/desenho-animado/perna-longa.webp',
      '/assets/images/desenho-animado/pica-pau.jpg',
      '/assets/images/desenho-animado/popeye.jpg',
      '/assets/images/desenho-animado/pucca.jpg',
      '/assets/images/desenho-animado/tom-e-jerry.webp',
    ],
  },
  {
    name: 'Animes',
    slug: 'animes',
    images: [
      '/assets/images/anime/attack-on-titan.webp',
      '/assets/images/anime/captain-tubasa.png',
      '/assets/images/anime/cavaleiros-do-zodiaco.png',
      '/assets/images/anime/demons-slayer.avif',
      '/assets/images/anime/dragon-ball.webp',
      '/assets/images/anime/jujutsu-kaisen.webp',
      '/assets/images/anime/minha-academia.jpeg',
      '/assets/images/anime/naruto.webp',
      '/assets/images/anime/one-piece.png',
      '/assets/images/anime/yugioh.webp',
    ],
  },
  {
    name: 'Pokemon',
    slug: 'pokemon',
    images: [
      '/assets/images/pokemon/ash.png',
      '/assets/images/pokemon/bulbasaur.png',
      '/assets/images/pokemon/charizard.png',
      '/assets/images/pokemon/jigglypuff.png',
      '/assets/images/pokemon/meowth.png',
      '/assets/images/pokemon/mew.png',
      '/assets/images/pokemon/pikachu.jpg',
      '/assets/images/pokemon/raichu.webp',
      '/assets/images/pokemon/rattata.png',
      '/assets/images/pokemon/squirtle.png',
    ],
  },
];
